services:
  app1: &app
    # build:
    #   context: ./app/
    image: lucasmocerinomonteiro/golang-rinha-backend
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: 123
      DB_NAME: rinha
      DB_PORT: 5432
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "20MB"

  app2:
    <<: *app

  proxy:
    image: nginx
    depends_on:
      - app1
      - app2
    ports:
      - 9999:9999
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "150MB"

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinha
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "360MB"
